 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/validations", type: :request do
  
  # Validation. As you add validations to Validation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Validation.create! valid_attributes
      get validations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      validation = Validation.create! valid_attributes
      get validation_url(validation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_validation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      validation = Validation.create! valid_attributes
      get edit_validation_url(validation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Validation" do
        expect {
          post validations_url, params: { validation: valid_attributes }
        }.to change(Validation, :count).by(1)
      end

      it "redirects to the created validation" do
        post validations_url, params: { validation: valid_attributes }
        expect(response).to redirect_to(validation_url(Validation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Validation" do
        expect {
          post validations_url, params: { validation: invalid_attributes }
        }.to change(Validation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post validations_url, params: { validation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested validation" do
        validation = Validation.create! valid_attributes
        patch validation_url(validation), params: { validation: new_attributes }
        validation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the validation" do
        validation = Validation.create! valid_attributes
        patch validation_url(validation), params: { validation: new_attributes }
        validation.reload
        expect(response).to redirect_to(validation_url(validation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        validation = Validation.create! valid_attributes
        patch validation_url(validation), params: { validation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested validation" do
      validation = Validation.create! valid_attributes
      expect {
        delete validation_url(validation)
      }.to change(Validation, :count).by(-1)
    end

    it "redirects to the validations list" do
      validation = Validation.create! valid_attributes
      delete validation_url(validation)
      expect(response).to redirect_to(validations_url)
    end
  end
end
